name: firstfloor_calendar
description: RFC 5545 compliant iCalendar (.ics) parser for Dart and Flutter.
version: 1.0.7
repository: https://github.com/firstfloorsoftware/firstfloor_calendar
topics:
  - icalendar
  - calendar
  - ics
  - rfc5545
  - recurrence

environment:
  sdk: ^3.8.1

dependencies:
 collection: ^1.19.1
 timezone: ^0.10.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3